version: '3'

services:
    postgres-red:
        image: postgres:12.0-alpine
        restart: always
        env_file: dbenv
        volumes:
            - './pgdata:/var/lib/postgresql/data'

    redmine:
        image: redmine:3.4-alpine
        restart: always
        depends_on:
            - postgres-red
        env_file: env
        ports:
            - '3000:3000'
        volumes:
            - './files:/usr/src/redmine/files'
            - './plugins:/usr/src/redmine/plugins'
            - './themes:/usr/src/redmine/public/themes'
